[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pyitm"
description = "Some code to help manage ITM outputs"
authors = [{name = "Aarons"}]
version="0.0.1"